export type MarkdownCommand =
  | 'heading-one'
  | 'heading-two'
  | 'bold'
  | 'italic'
  | 'strike'
  | 'link'
  | 'quote'
  | 'bullet-list'
  | 'numbered-list'
  | 'task-list'
  | 'inline-code'
  | 'code-block'
  | 'image'
